parameters:
#    centrohipico.example.class: Sunahip\CentrohipicoBundle\Example

services:
#    centrohipico.example:
#        class: %centrohipico.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    data_operadaroa_establecimiento_model:
        class: Sunahip\CentrohipicoBundle\Model\DataOperadoraEstablecimientoModel
        arguments: [@doctrine.orm.entity_manager]
