<?php

namespace Sunahip\EntityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdmAporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdmAporteRepository extends EntityRepository
{
}
