<?php

namespace Sunahip\EntityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdmClasfEstabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdmClasfEstabRepository extends EntityRepository
{
}
