<?php

namespace Sunahip\EntityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DataSucursalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataSucursalRepository extends EntityRepository
{
}
