<?php
/**
 * Traits:      Trait para entidades con identificador autoincrementable
 *
 * @package     Sunahip
 * @subpackage  Common
 * @author      Reynier Perez Mira <reynierpm@gmail.com>
 */

namespace Sunahip\CommonBundle\Model;

use Doctrine\ORM\Mapping as ORM;

trait IdentifiedAutogeneratedEntityTrait
{

    /**
     * @ORM\Id
     * @ORM\Column(type="integer",unique=true,nullable=false)
     * @ORM\GeneratedValue
     */
    protected $id;

    public function getId()
    {
        return $this->id;
    }

}
