export:
    resource: "@ExportBundle/Resources/config/routing.yml"
    prefix:   /

reporte:
    resource: "@ReporteBundle/Controller/"
    type:     annotation
    prefix:   /informe

pagos:
    resource: "@PagosBundle/Controller/"
    type:     annotation
    prefix:   /
    options:
        expose: true

fiscalizacion:
    resource: "@FiscalizacionBundle/Resources/config/routing.yml"
    prefix:   /

centrohipico:
    resource: "@CentrohipicoBundle/Resources/config/routing.yml"
    prefix:   /

new_template:
    resource: "@NewTemplateBundle/Resources/config/routing.yml"
    prefix:   /

solicitudes_citas:
    resource: "@SolicitudesCitasBundle/Resources/config/routing.yml"
    prefix:   /

licencia:
    resource: "@LicenciaBundle/Controller/"
    type:     annotation
    prefix:   /licencia/

common:
    resource: "@CommonBundle/Controller/"
    type:     annotation
    options:
        expose: true

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    options:
        expose: true

# FOSUserBundle Routes
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

#FOSJsRouting
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

EndroidQrCodeBundle:
    resource:   "@EndroidQrCodeBundle/Controller/"
    type:       annotation
    prefix:     /qrcode
