<?php

namespace Sunahip\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DataCentrohipicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SysUsuarioRepository extends EntityRepository
{
    public function findByAction($keyword = null, $role = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select("su")
           ->from("UserBundle:SysUsuario", "su");

        if ($keyword) {
            $where = $qb->expr()->orX(
                $qb->expr()->like('su.username', "'%" . $keyword . "%'"),
                $qb->expr()->like('su.fullname', "'%" . $keyword . "%'"),
                $qb->expr()->like('su.email', "'%" . $keyword . "%'")
            );
            $qb->where($where);
        }
        if (!empty($role)) {
            $qb->innerJoin("UserBundle:SysPerfil", "sp", "WITH", "sp.user = su.id");
            $qb->andWhere("sp.roleType = :perfil");
            $qb->setParameter("perfil", $role);
        }

        return $qb->getQuery()->getResult();
    }


    public function findByRole($role) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
            ->from('UserBundle:SysUsuario', 'u')
            ->where('u.roles LIKE :roles')
            ->setParameter('roles', '%"' . $role . '"%');
        return $qb->getQuery()->getResult();
    }
}
