<?php

namespace Sunahip\SolicitudesCitasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DataSolicitudesAprobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataSolicitudesAprobRepository extends EntityRepository
{
    public function getAprobadas($operadora=null, $centroHipico=null) {
        $q = $this->getEntityManager()->createQueryBuilder();
        $q->select('sa')
            ->from("SolicitudesCitasBundle:DataSolicitudesAprob","sa")
            ->innerJoin("SolicitudesCitasBundle:DataSolicitudes", "s", "WITH", "s.id = sa.solicitud")
            ->where("s.status = :status")
            ->setParameter("status", "Aprobada");
        if($operadora !== null) {
            $q->andWhere("s.operadora = :operadora")
                    ->setParameter("operadora", $operadora);
        }else {
            $q->andWhere("s.centroHipico = :centroHipico")
                    ->setParameter("centroHipico", $centroHipico);
        }
        return $q->getQuery()->getResult();
    }
}