<?php

namespace Sunahip\CentrohipicoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DataOperadoraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataOperadoraEstablecimientoRepository extends EntityRepository
{

    public function findByAction($user =  null , $keyword = null, $status = null)
    {

        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('doe.id','doe.status','dc.persJuridica','dc.rif','dc.denominacionComercial','do.denominacionComercial as operadora' ,'ce.clasfLicencia as licencia')
            ->from("CentrohipicoBundle:DataOperadoraEstablecimiento", "doe")
            ->innerJoin("CentrohipicoBundle:DataOperadora", "do", "WITH", "do.id = doe.operadora")
            ->innerJoin("CentrohipicoBundle:DataCentrohipico", "dc", "WITH", "dc.id = doe.centroHipico")
            ->leftJoin("LicenciaBundle:AdmClasfLicencias", "ce", "WITH", "ce.id = doe.clasLicencia")
            ->orderBy("doe.fechaDesafiliacion", "DESC");
        if($user)
        {
            $qb->where("doe.usuario = ?1")
            ->setParameter(1, $user);
        }
        if (!empty($keyword)) {
            $where = $qb->expr()->orX(
                $qb->expr()->like('dc.denominacionComercial', "'%" . $keyword . "%'"),
                $qb->expr()->like('dc.rif', "'%" . $keyword . "%'")
            );

            if($user)
                $qb->andWhere($where);
            else
                $qb->where($where);
        }
        if (!empty($status)){
            $qb->andWhere("doe.status = ?2")
                    ->setParameter(2, $status);
        }

        return $qb->getQuery()->getResult();
    }
    
    public function findSolicitudAfiliacion($centroHipico, $operadora, $licencia)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('doe.id','doe.status')->from("CentrohipicoBundle:DataOperadoraEstablecimiento", "doe")
                ->andWhere("doe.centroHipico = :centroHipico")
                ->andWhere("doe.operadora = :operadora")
                ->andWhere("doe.clasLicencia = :licencia")
                ->setParameter("centroHipico", $centroHipico)
                ->setParameter("operadora", $operadora)
                ->setParameter("licencia", $licencia);
        
        $where =    $qb->expr()->orX(
                        $qb->expr()->eq("doe.status", "'Aprobado'"),
                        $qb->expr()->eq("doe.status", "'Por Aprobar'"),                        
                        $qb->expr()->eq("doe.status", "'Por Desafiliar'")
                    );
        $qb->andWhere($where);
        return $qb->getQuery()->getResult();        
    }
    
    public function findByOperadora($operadora) {        
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('doe')
                ->from("CentrohipicoBundle:DataOperadoraEstablecimiento", "doe")
                ->andWhere("doe.operadora = :operadora")
                ->setParameter("operadora", $operadora);        
        $where = $qb->expr()->orX(
                    $qb->expr()->eq("doe.status", "'Aprobado'"),                       
                    $qb->expr()->eq("doe.status", "'Por Desafiliar'")
                 );
        $qb->andWhere($where);
        return $qb->getQuery()->getResult();        
    }

}
