<?php

namespace Sunahip\CentrohipicoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DataCentrohipicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataCentrohipicoRepository extends EntityRepository
{
    public function getOwnedCH($user){
        return $this->findBy(array("usuario"=>$user->getId()));
    }

    public function findByAction($rifType,$rifNumber, $denominacionComercial = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select("ch")
            ->from("CentrohipicoBundle:DataCentrohipico", "ch")
            ->where('ch.persJuridica  = :rifType')
            ->andWhere('ch.rif = :rifNumber')
            ->setParameter('rifType', $rifType)
            ->setParameter('rifNumber', $rifNumber);;

        if ($denominacionComercial) {
            $where = $qb->expr()->orX(
                $qb->expr()->like('ch.denominacionComercial', "'%" . $denominacionComercial . "%'")
            );
            $qb->andWhere($where);
        }

        return $qb->getQuery()->getResult();
    }
    
     /**
     * Busca por tipo de campo
     * @param  string $tipo  [description]
     * @param  string $valor [description]
     * @return [type]        [description]
     */
    public function buscar($tipo, $valor){
        $q = $this->createQueryBuilder('u');
        $q->where("u.$tipo LIKE  :id")
            ->setParameter('id', "%$valor%");
        return $q->getQuery()->getResult();
    }
}
