<?php

namespace Sunahip\CentrohipicoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DataOperadoraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataOperadoraRepository extends EntityRepository
{
    
    public function contSucursales($user) {
         $query = $this->createQueryBuilder('S')
            ->select('count(S.id) as cant')
            ->set("S.usuario", $user)    
            ->set("S.esSucursal", '1')     
            ->getQuery();
            $resp=$query->getOneOrNullResult();
            //var_dump($resp);
            //die();
        return $resp['cant'];
    }
}
