<?php

namespace Sunahip\CentrohipicoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DataLegalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataLegalRepository extends EntityRepository
{
}
